name: ch58x-toolchain-ci

on:
  workflow_dispatch:

jobs:
  mktoolchain:
    strategy:
      fail-fast: false

    runs-on: ubuntu-22.04

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "20G"
          create-symlink: true
          key: ${{matrix.os }}-${{ matrix.type }}

      - name: Create Timestamp
        run: |
              echo "BUILD_ID=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
              echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Install Software
        run: |
              sudo apt update && \
              sudo apt install -y build-essential autoconf automake autotools-dev ninja-build make help2man \
                                  libncurses-dev gawk flex bison openssl libssl-dev tree wget curl cmake ccache \
                                  libtool-bin bc bzr ca-certificates cmake cpio cvs file git locales mercurial \
                                  openssh-server python3 python3-flake8 python3-magic python3-nose2 python3-pexpect \
                                  python3-pytest rsync shellcheck subversion unzip

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
            path: 'gdiv10-toolchain'  # TODO: make this name a global variable

      - name: Build crosstool-ng
        run: |
              export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
              ccache -s
              wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.26.0.tar.xz
              tar xf crosstool-ng-1.26.0.tar.xz
              pushd crosstool-ng-1.26.0
                ./configure --enable-local
                make -j$(nproc)
              popd

      - name: Make Toolchain
        run: |
              export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
              pushd crosstool-ng-1.26.0
                cp ../gdiv10-toolchain/crosstool-ng/riscv32-ch58x-elf.config .config
                ./ct-ng upgradeconfig
                ./ct-ng build -j$(nproc) &> ../crosstool-ng_build.log
                ccache -s
                rm -rf .build/
                df -h
                xz -z -v -9 ../crosstool-ng_build.log
              popd

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          retention-days: 30
          name: riscv32-ch58x-elf-toolchain-${{ env.BUILD_ID }}
          path: |
                  crosstool-ng-1.26.0/*.tar.xz
                  crosstool-ng-1.26.0/*.tar.xz.asc
                  crosstool-ng_build.log.xz
